name: Trunk Upgrade

on:
  schedule:
    # On the first day of every month @ 8am
    - cron: 0 8 1 * *
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  trunk-upgrade:
    name: trunk upgrade
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed by github-action-trunk-upgrade to write repository contents
      pull-requests: write # needed by github-action-trunk-upgrade to write pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run Trunk Upgrade
        uses: ./ # Use the local action for self-testing
        with:
          app-id: ${{ secrets.MP_BOT_APP_ID }}
          app-private-key: ${{ secrets.MP_BOT_APP_PRIVATE_KEY }}
          github-token: ${{ secrets.MASTERPOINT_TEAM_PAT }}
          reviewers: "@masterpointio/masterpoint-open-source"
